#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run prettier to format code
npm run format

# Run eslint with auto-fix
npm run lint

# Add any formatted/fixed files back to the commit
git add .
